apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-location
data:
  CLUSTER_ID: east
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-deployment 
spec:
  selector:
    matchLabels:
      app: cluster-loc 
  replicas: 20 
  template:
    metadata:
      labels:
        app: cluster-loc
    spec:
      containers:
      - name: server
        image: seaweed39kelp/poctesting:1.0 
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: cluster-location
