apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-proxy-service
data:
  PROXY_SERVICE: cluster-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-proxy 
spec:
  selector:
    matchLabels:
      app: cluster-proxy 
  replicas: 5 
  template:
    metadata:
      labels:
        app: cluster-proxy 
    spec:
      containers:
      - name: server
        image: seaweed39kelp/poctestingproxy:0.5 
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: cluster-proxy-service
---
apiVersion: v1
kind: Service
metadata:
  name: poc-cluster-proxy 
spec:
  type: NodePort
  selector:
    app: cluster-proxy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30019
