apiVersion: v1
kind: Service
metadata:
  name: cluster-service
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/shared: "true"
spec:
  type: ClusterIP
  selector:
    app: cluster-loc
  ports:
    - port: 80
